name: Cross compile WireProxy

on:
  workflow_dispatch:
  create:
     tags:
       - v*

jobs:
  WireProxy:

    name: Cross compile WireProxy

    runs-on: ubuntu-20.04

    env:
      workdir: ./WireProxy

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Git clone WireProxy
        run: |
          git clone https://github.com/pufferffish/wireproxy.git ${{ env.workdir }}
          cp ./.github/wireproxy-releaser.yml ${{ env.workdir }}/.goreleaser.yml

      - name: Set up GoReleaser
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          workdir: ${{ env.workdir }}
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          tag_name: wireproxy
          files: ${{ env.workdir }}/dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
